### ISSUE TITLE
Chart does not display colors until legend item is selected / unselected.

### ISSUE THREAD

**Issue by neomewilson** [DmitrySharabin/mavo-chart#5]
First of all, my compliments on Mavo. I simply love it! Please don't stop developing this framework. Now to the issue. I am developing a web app for making decisions. This app will allow you to enter criteria and weights if wanted to display which decision is better based on data. I am including all my code so you can play with it and see if  the issue can be duplicated. 

**_The Issue:_**

When I display a chart using the chart plugin with Mavo, it displays in grayscale without colors at all. If you select one of the legend series, the color for the chart will appear but the legend is still without colors. If you unselect the legend it displays colors for both the chart and legend. 

At that point if you close and reopen the chart it will display everything with color because the browser has it cached. If you refresh the page and display it again, it will be back to grayscale. I have tested this in the latest releases of Edge, Chrome and Firefox. All perform the same way. 

**Important Note:** I am using a CSS Framework with Mavo called Cirrus. I have tried it without the framework to eliminate it as a cause. It still has the same issue. 

Here is the code. It is not a completed web app but it is fully functional at this point. 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>What to do?</title>
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cirrus-ui@0.5.5/dist/cirrus.min.css">
    <script src="https://get.mavo.io/mavo.js"></script>
  
</head>

<body>
    <main mv-app="Decisions" mv-plugins="chart" mv-storage="local" mv-autosave="0"> 
        <div class="card" style="max-width: 80%; margin: auto; padding: 10px;">
            <div class="card-head" style="background: rgb(191, 196, 201);">
                <h3> What to do? - </h3>
                    <h5 class="card-head-title">
                        Decision Matrix - Measuring Possible Outcomes!
                    </h5> 
            </div>
            <div class="subtitle">
                <p class="card-text" style="padding: 10px; text-align: left; font-size: medium;">
                    Use this to provide your criteria, weights and allow it to determine the possible outcome.
                    <b>Note:</b> <i>Using weights will add the values to the calculated result, keeping them at zero will ignore them.</i>
                    <hr style="width: 100%; text-align: left;"> 

                </p>
            </div>

            <div class="content">
                <aside class="mv-bar">
                    <div class="btn-container">
                        <div class="mv-edit btn btn-black btn-animated">Edit table data</div>
                    </div>
                </aside>                    
                <table class="table striped bordered">
                    <thread>
                        <tr>
                            <th scope="col">Criteria</th>
                            <th scope="col">Baseline</th>
                            <th scope="col">Weight</th>
                            <th scope="col">Evaluate 1</th>                            
                            <th scope="col">Evaluate 2</th>
                            <th scope="col">Evaluate 3</th>
                            <th scope="col">Evaluate 4</th>
                        </tr> 
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>
                                <input type="text" placeholder="My Evaluate label" maxlength="15" size="15"/>
                            </th>
                            <th>
                                <input type="text" placeholder="My Evaluate label"  maxlength="15" size="15" />
                            </th>
                            <th>
                                <input type="text" placeholder="My Evaluate label"  maxlength="15" size="15"/>
                            </th>
                            <th>
                                <input type="text" placeholder="My Evaluate label"  maxlength="15" size="15"/>
                            </th>
                        </tr>
                    </thread>

                    <tbody> 
                        <tr property="DecisionResults" mv-multiple>
                            <div class="form-group">
                                <p style: margin="5px"></p>
                                <label for="decisionscenario">Decision Scenario</label>
                                <p style: margin="5px"></p>
                                <textarea property="DecisionScenario" class="formcontrol" style="width: 100%; height: 200px;"></textarea> 
                            </div>
                            <div>
                                <th property="Criteria"></th>
                                <th property="Baseline"></th>
                                <th property="Weight"></th>
                                <th property="Evaluate_1"></th>
                                <th property="Evaluate_2"></th>
                                <th property="Evaluate_3"></th>
                                <th property="Evaluate_4"></th> 
                            </div>
                        </tr>
                    </tbody>
                </table>
                <div>
                    <a href="#DecisionChart">
                        <button>Graph</button>
                    </a>
                </div>      
            </div>

            <div class="modal modal-large modal-animated--zoom-in max-width: 80rem;" id="DecisionChart">
                <a href="#target" class="modal-overlay close-btn" aria-label="Close"></a>
                <div class="modal-content" role="document">
                    <div class="modal-header">
                        <a href="#components" class="u-pull-right" aria-label="Close">
                            <span class="icon">
                                <i class="fa fa-wrapper fa-times"></i>
                            </span>
                        </a>
                        <div class="modal-title">Decision Results Chart</div>
                    </div>
                    <div class="modal-body">  
                        <canvas 
                            mv-chart-type="horizontalBar" width="1000" height="500"                            
                            mv-chart-title="Your Decision"
                            mv-chart-data="[get(DecisionResults, 'Evaluate_1')]; [get(DecisionResults, 'Evaluate_2')]; [get(DecisionResults, 'Evaluate_3')]; [get(DecisionResults, 'Evaluate_4')]"
                            mv-chart-labels="[get(DecisionResults, 'Criteria')]" 
                            mv-expressions-ignore="mv-chart-series-styles"
                            mv-chart-legend="Evaluate_1, Evaluate_2, Evaluate_3, Evaluate_4"
                            mv-chart-legend-position="bottom"
                            mv-chart-theme="tableau.Classic10">
                            <p>Your browser doesn't support charts in canvas!</p>
                        </canvas>
                    </div>  
                </div> 
            </div>
    </main>
</body>

</html> `

I am including screenshots as well so you can follow the sequence and use the same data if you want to produce the results I am getting:

**Main App Shot with Data:**

![DecisionWebApp](https://user-images.githubusercontent.com/40023678/82568859-0bb9dc00-9b45-11ea-9647-ee2451ed5a31.JPG)

**Main App:**

![DecisionAppError](https://user-images.githubusercontent.com/40023678/82569062-53d8fe80-9b45-11ea-8c1a-c66f93a78a64.JPG)

**Grayscale initial display of Graph:**

![GrayChartMavo](https://user-images.githubusercontent.com/40023678/82569253-9995c700-9b45-11ea-9e6c-e71ff0d05875.JPG)

**Selecting a legend series to display color on chart:**

![PartialColorMavo](https://user-images.githubusercontent.com/40023678/82569326-b500d200-9b45-11ea-978d-e67d050a9a98.JPG)

**Unselecting legend to to display all colors:**

![FullColorMavo](https://user-images.githubusercontent.com/40023678/82569387-ca75fc00-9b45-11ea-84c7-82487000a7f6.JPG)

I have tried this using the modal or not. Without modal it will sometimes display the colors on the chart but not the legend. 

Hardware: I use a gaming desktop as my development machine. It has 32GB RAM, 4 GZ CPU, 1080TI Video Card, 3 Drives of which 2 are SD drives. I don't think it is related to anything like lack of hardware resources. 

I appreciate you looking into this. I have other avenues I can go if this simply won't work but I really would like to stay with Mavo for this web app vs. switching to VUE or something more complex to use.

**Comment by DmitrySharabin** [comment]
@neomewilson 
Hey there! 👋🏻
I am terribly sorry for not answering earlier—GitHub hasn't notified me that you had filed the issue. 😞 And thank you for using Mavo and this plugin.

The problem you face is a known issue—its source is the Colorschemes plugin that lets us use color themes. I tried to solve but unfortunately failed. I'll give it another try. Please stay in touch.

**Comment by DmitrySharabin** [comment]
I hope I could finally fix this issue. 🤞 
Feel free to reopen it if I am wrong.

**Comment by neomewilson** [comment]
I have responded with new code to see if I am not understanding something
about how this works. I didn't know how to change the status so it's still
under the closed status.

**Comment by DmitrySharabin** [comment]
Hey! 👋🏻

I got your message and will take a look at your code asap. I'll let you know when I finish. Will do my best to help you.

**Comment by neomewilson** [comment]
Just a little extra help. When you display the page, there will be an icon in the right-hand side. Select that icon and it will perform a Card-Reveal which you'll see in the code as one of the classes. That is what displays the card that is suppose to display the graph. 
![MavoScreenshot](https://user-images.githubusercontent.com/40023678/84702083-b4c4de00-af1b-11ea-884d-6323d4c3c35d.JPG)

**Comment by neomewilson** [comment]
Dmitry,

I took a different approach and solved the issue of the not appearing chart. I could not resolve the card-reveal issue. Something is interfering with the chart when using this method from materialize but I used a link to a separate .html file and it works great. I have included code from 3 different files so the complete project works. Now I can complete the initial prototype application. Hurray...

Here is the main file you'll need:

`<!DOCTYPE html>
<html lang="en">

<head>
    
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css" />
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">    
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Decisions</title>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <script src="https://get.mavo.io/mavo.js"></script>
    
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>

<body>  

    <main mv-app="Decisions" mv-storage="local" mv-autosave="0" mv-plugins="chart">
    <div class="col s12 m6">
        <div class="card sticky-action" style="overflow: hidden; margin: 20px;">
            <div class="card-content;" style="width: 100%;">
                <nav>
                    <div class="nav-wrapper">
                        <span class="card-title activator grey-text text-darken-4" style="padding: 10px;"><b style="padding: 80px;">Decision Matrix - Measuring Possible Outcomes!</b>
                        </span>
                      <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a href="qanda.html">Questions & Answers</a></li>
                      </ul>
                    </div>
                  </nav>
                <div id="basic-form" class="section">
                    <div class="row">
                        <div class="col s12 m12">
                            <div class="card-panel" style="width: 95%; height: 70%; padding: 10px; margin: 25px 40px 25px 40px;">
                                <span class="card-title grey-text text-darken-4"><h6><b>Decision Matrix</b></h6><a class = "btn-floating waves-effect waves-light red lighten-2 right" href="chart.html"><i class = "small material-icons right">assessment</i></span></a> 
                                <div class="row">
                                    <form class="col s12">
                                        <div class="row">                                            
                                                <aside class="mv-bar">
                                                    <p>
                                                    <div class="btn-container">
                                                        <div class="mv-edit btn btn-black btn-animated">Edit table data
                                                        </div>
                                                    </div>
                                                    </p>
                                                </aside>
                                                <table class="responsive-table highlight bordered">
                                                    <thread>
                                                        <tr>
                                                            <th scope="col">Criteria</th>
                                                            <th scope="col">Baseline</th>
                                                            <th scope="col">Weight</th>
                                                            <th scope="col">Rank</th>
                                                            <th scope="col">Evaluate 1</th>
                                                            <th scope="col">Evaluate 2</th>
                                                            <th scope="col">Evaluate 3</th>
                                                            <th scope="col">Evaluate 4</th>
                                                        </tr>
                                                        <tr>
                                                            <th></th>
                                                            <th></th>
                                                            <th></th>
                                                            <th></th>
                                                            <th>
                                                                <input type="text" placeholder="My Evaluate label"
                                                                    maxlength="15" size="15" />
                                                            </th>
                                                            <th>
                                                                <input type="text" placeholder="My Evaluate label"
                                                                    maxlength="15" size="15" />
                                                            </th>
                                                            <th>
                                                                <input type="text" placeholder="My Evaluate label"
                                                                    maxlength="15" size="15" />
                                                            </th>
                                                            <th>
                                                                <input type="text" placeholder="My Evaluate label"
                                                                    maxlength="15" size="15" />
                                                            </th>
                                                        </tr>
                                                    </thread>
                                                    <tbody>
                                                        <tr property="DecisionResults" mv-multiple>
                                                            <p style="padding: 5px;"></p>
                                                            <div class="input-field col s10">
                                                                <i class="material-icons prefix">mode_edit</i>
                                                                <textarea property="DecisionScenario" id="icon_prefix2"
                                                                    class="materialize-textarea"
                                                                    style="width: 100%; height: 100px;"></textarea>
                                                                <label for="icon_prefix2">Decision Scenario</label>
                                                            </div>
                                                            </p>
                                                            <div>
                                                                <th property="Criteria"></th>
                                                                <th property="Baseline"></th>
                                                                <th property="Weight"></th>
                                                                <th property="Rank"></th>
                                                                <th property="Evaluate_1")></th>
                                                                <th property="Evaluate_2"></th>
                                                                <th property="Evaluate_3"></th>
                                                                <th property="Evaluate_4"></th>
                                                            </div>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                    <div class="card-panel">
                    <footer class="page-footer">
                            <div class="row">
                                <div class="col l6 s12">
                                    <table class="responsive-table highlight bordered">
                                        <thread>
                                            <tr>
                                                <th scope="col">Total +</th>
                                                <th scope="col">Total ++</th>
                                                <th scope="col">Total -</th>
                                                <th scope="col">Total --</th>
                                                <th scope="col">Total Weighted</th>
                                                <th scope="col">Total Ranked</th>
                                                <th scope="col">Total Score</th>
                                            </tr>
                                        </thread>
                                        <tbody>
                                            <tr property="DecisionTotals" mv-multiple>
                                                <p style="padding: 5px;"></p>
                                                </p>
                                                <div>
                                                    <th property="TotalPlus"></th>
                                                    <th property="TotalPlusPlus"></th>
                                                    <th property="TotalMinus"></th>
                                                    <th property="TotalMinusMinus"></th>
                                                    <th property="TotalWeighted"></th>
                                                    <th property="TotalRanked"></th>
                                                    <th property="TotalScore"></th>
                                                </div>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
        </div>
    </main>  
</body>

</html>`

This is the chart file that will be called when selecting the icon located on the top-right inside the round button. 

`<!DOCTYPE html>
<html lang="en">

<head>
    
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css" />
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">    
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Decisions</title>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <script src="https://get.mavo.io/mavo.js"></script>
    
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>

<body>

<div>
    <main mv-app="Decisions" mv-storage="local" mv-autosave="0" mv-plugins="chart">
        <div class="col s12 m6">
            <div class="card sticky-action" style="overflow: hidden; margin: 20px;">
                <div class="card-content;" style="width: 100%;">
                    <nav>
                        <div class="nav-wrapper">
                            <span class="card-title activator grey-text text-darken-4" style="padding: 10px;"><b style="padding: 80px;">Decision Matrix - Measuring Possible Outcomes!</b>
                            </span>
                          <ul id="nav-mobile" class="right hide-on-med-and-down">
                            <li><a href="qanda.html">Questions & Answers</a></li>
                          </ul>
                        </div>
                    </nav>
                </div>
            </div>
            <div class="card">              
                <div class="card-panel" id="ResultsChart" style="width: 90%; padding: 10px; margin: 25px 80px 25px 80px;">
                    <span class="card-title grey-text text-darken-4"><p style="padding: 10px; margin: 5px;"><b>Chart Decision Results</b></p><a class = "btn-floating waves-effect waves-light red lighten-2 right" href="whattodo.html"><i class="material-icons right">close</i></span></a>  
                    <canvas                                                        
                        mv-chart-type="horizontalBar" width="1000" height="450"                    
                        mv-chart-title="Your Decision"
                        mv-chart-data="[get(DecisionResults, 'Evaluate_1')]; [get(DecisionResults, 'Evaluate_2')]; [get(DecisionResults, 'Evaluate_3')]; [get(DecisionResults, 'Evaluate_4')]"
                        mv-chart-labels="[get(DecisionResults, 'Criteria')]" 
                        mv-expressions-ignore="mv-chart-series-styles"
                        mv-chart-legend="Evaluate_1, Evaluate_2, Evaluate_3, Evaluate_4"
                        mv-chart-legend-position="bottom"
                        mv-chart-theme="brewer.DarkTwo8">                                             
                    </canvas>
                </div>                
            </div>
</div>

    </main>  
</body>

</html>`

Here is the help file for the Questions and Answer response plus the jpg file you'll need as a resource for it.

`<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/css/materialize.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/js/materialize.min.js"></script>

</head>

<body> 
    <div class="col s12 m6">
        <div class="card sticky-action" style="overflow: hidden; margin: 20px;">
            <div class="card-content;" style="width: 100%;">
                <nav>
                    <div class="nav-wrapper">
                        <span class="card-title activator grey-text text-darken-4" style="padding: 10px;"><b style="padding: 80px;">Decision Matrix - Measuring Possible Outcomes!</b>
                        </span>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">

                        <li><a href="whattodo_Materialize.html">Home</a></li>
                    </ul>
                    </div>
                </nav>
            </div>
            <div class="container">
                <div class="card-panel">
                    <ul class="collapsible popout">
                        <li>
                        <div class="collapsible-header"><i class="left material-icons">list</i>Understanding the Matrix</div>
                        <div class="collapsible-body"><span><img src="../Mavo/docs/Howto.JPG" style="display: block; margin-left: auto; margin-right: auto"></span></div>
                        </li>
                        <li>
                        <div class="collapsible-header"><i class="material-icons">playlist_add</i>What's Criteria?</div>
                        <div class="collapsible-body"><span>The content for second panel comes here!</span></div>
                        </li>
                        <li>
                        <div class="collapsible-header"><i class="material-icons">playlist_play</i>What's Alternatives</div>
                        <div class="collapsible-body"><span>The content for third panel comes here!</span></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<script>
 $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>
</body>   
</html>`

I am attaching all the files plus the resource file if you want to look at the project. I am pretty excited about this now that this is solved. I am not a great coder but I am persistent and I am a great problem solver. I got paid for that skill more than anything else in my 35 year IT career. 



[Decision.zip](https://github.com/DmitrySharabin/mavo-chart/files/4789205/Decision.zip)

**Comment by DmitrySharabin** [comment]
Yay! What excellent news. Congratulations, Michael! 🥳

That's so cool to know that Mavo helps people solve their problems. Your app looks really great! 👍🏻 If you'll host it somewhere and will decide to share it with others, please tweet about it and mention @mavoweb or simply let me know, and I tweet about it myself. We want to know how people use Mavo in the wild and would love to see how and what they do.

**Comment by neomewilson** [comment]
Thanks, I will let you know when the initial app is completed. I plan on
hosting it for a small group so I can get user testing and feedback. Once I
am through that initial phase I will share the hosting link with you. I
plan on the initial project to be free so I can understand use cases of how
it might be used and fixes I might need to do. There might be some future
state where I charge but that is likely pretty far down the line. I do
appreciate all your assistance and look forward to completing this project
with authentication, profiles and eventually the ability to track the
performance of your decisions you model.

Best Regards,

Michael
